FoodBlogs/Controllers/DrinksController.cs
using FoodBlogs.Business_Layer;
using FoodBlogs.JsonClass;
using FoodBlogs.Models.MyModel;
using FoodBlogs.Web_Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserLibrary;

namespace FoodBlogs.Controllers
{
    public class DrinksController : BaseController
    {
        // GET: Drinks
        public ActionResult Index()
        {
            List<Cocktail> lstCocktail = new List<Cocktail>();
            CocktailHeaderJsonClass drinksJsonClass = new CocktailHeaderJsonClass();
            ConsumingWebService cocktailWebService = new ConsumingWebService();
            drinksJsonClass = cocktailWebService.CallNonAlcoholicCocktailWebService();

            Cocktail cocktail = null;
            foreach (CocktailHeader cocktailHeader in drinksJsonClass.ilstCocktailHeader)
            {
                cocktail = new Cocktail();
                cocktail.CocktailId = Convert.ToInt32(cocktailHeader.idDrink);
                cocktail.CocktailName = cocktailHeader.strDrink;
                cocktail.CocktailUrl = cocktailHeader.strDrinkThumb;
                lstCocktail.Add(cocktail);
            }

            drinksJsonClass = cocktailWebService.CallAlcoholicCocktailWebService();
            foreach (CocktailHeader cocktailHeader in drinksJsonClass.ilstCocktailHeader)
            {
                cocktail = new Cocktail();
                cocktail.CocktailId = Convert.ToInt32(cocktailHeader.idDrink);
                cocktail.CocktailName = cocktailHeader.strDrink;
                cocktail.CocktailUrl = cocktailHeader.strDrinkThumb;
                lstCocktail.Add(cocktail);
            }

            lstCocktail = lstCocktail.OrderBy(x => x.CocktailName).ToList();
            return View(lstCocktail);

        }

        public ActionResult Detail(int aintId)
        {
            CocktailWebService webService = new CocktailWebService();
            Business_Logic lBusiness_Logic = new Business_Logic();
            CocktailDetailJsonClass cocktailDetailJson = new CocktailDetailJsonClass();
            cocktailDetailJson = webService.CocktailDetailWebService(aintId);
            string lstrIngredient = string.Empty;
            CocktailDetail cocktailDetail = new CocktailDetail();
            cocktailDetail.istrDrinkId = cocktailDetailJson.ilstCocktailDetail[0].idDrink;
            cocktailDetail.istrDrinkName = cocktailDetailJson.ilstCocktailDetail[0].strDrink;
            cocktailDetail.istrDrinkThumb = cocktailDetailJson.ilstCocktailDetail[0].strDrinkThumb;
            cocktailDetail.ilstIngredients = new List<string>();
            cocktailDetail.icomments = lBusiness_Logic.GetCommentlistByPostName();
            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient1))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient1;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure1))
                    lstrIngredient = lstrIngredient + " " +  cocktailDetailJson.ilstCocktailDetail[0].strMeasure1;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient2))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient2;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure2))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure2;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }
            
            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient3))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient3;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure3))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure3;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient4))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient4;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure4))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure4;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient5))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient5;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure5))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure5;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }
            
            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient6))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient6;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure6))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure6;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient7))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient7;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure7))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure7;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient8))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient8;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure8))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure8;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient9))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient9;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure9))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure9;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient10))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient10;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure10))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure10;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient11))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient11;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure11))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure11;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient12))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient12;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure12))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure12;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient13))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient13;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure13))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure13;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient14))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient14;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure14))
                    lstrIngredient = lstrIngredient + " " + cocktailDetailJson.ilstCocktailDetail[0].strMeasure14;
                cocktailDetail.ilstIngredients.Add(lstrIngredient);
            }

            if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strIngredient15))
            {
                lstrIngredient = cocktailDetailJson.ilstCocktailDetail[0].strIngredient15;
                if (!string.IsNullOrEmpty(cocktailDetailJson.ilstCocktailDetail[0].strMeasure15))

FoodBlogs/Views/Drinks/Detail.cshtml
@model FoodBlogs.Models.MyModel.CocktailDetail
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="Detail">
    <h2>@Model.istrDrinkName</h2>
    @if (Model.istrDrinkThumb != null && Model.istrDrinkThumb != "")
    {
        <img src=@Url.Content(Model.istrDrinkThumb) align="top" HSPACE="20" VSPACE="20" />
    }
    else
    {
        <img sr="" />
    }

    <h4>Ingredients</h4>
    <ul>
        @foreach (string strIngrdnt in Model.ilstIngredients)
        {
            <li>@strIngrdnt</li>
        }
    </ul>
    <h4>Instruction</h4>
    <p>@Model.istrInstructions</p>


</div>
<br />
<br />

@Html.Partial("_Comments", Model.icomments)

FoodBlogs/Views/Drinks/Index.cshtml
@model IEnumerable<FoodBlogs.Models.MyModel.Cocktail>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="px-lg-5">

        <!-- For demo purpose -->
        <div class="row py-5">
            <div class="col-lg-12 mx-auto">
                <div class="text-white p-5 shadow-sm rounded banner">
                    <h1 class="display-4">Bootstrap 4 photo gallery</h1>
                    <p class="lead">Bootstrap photogallery snippet.</p>
                    <p class="lead">
                        Snippet by <a href="https://bootstrapious.com/snippets" class="text-reset">
                            Bootstrapious
                        </a>, Images by <a href="https://unsplash.com" class="text-reset">Unsplash</a>.
                    </p>
                </div>
            </div>
        </div>
        <!-- End -->

        <div class="row">
            @foreach (FoodBlogs.Models.MyModel.Cocktail lCocktail in Model)
            {
                <!-- Gallery item -->
                <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
                    <div class="bg-white rounded shadow-sm">
                        <img src=@lCocktail.CocktailUrl alt="" class="img-fluid card-img-top">
                        <div class="p-4">
                            
                            <h5>@Html.ActionLink(lCocktail.CocktailName , "Detail" , "Drinks", new { aintId = lCocktail.CocktailId }, new { @class = "text-dark" })</h5>
                        </div>
                    </div>
                </div>
                <!-- End -->
            }
        </div>
        <div class="py-5 text-right"><a href="#" class="btn btn-dark px-5 py-3 text-uppercase">Show me more</a></div>
    </div>
</div>